#!/usr/bin/env bash
# install.sh — install simple-secret-storage in one command.
#
#   curl -sSL https://raw.githubusercontent.com/megamen32/simple-secret-storage/main/install.sh | bash
#
# Does:
#   - clone the repo into ~/agents-projects/simple-secret-storage
#   - npm ci + npm run build
#   - generate a fresh bearer token in ~/.config/sss-mcp/api-key.env
#   - install + enable systemd unit (uses /usr/local/bin/node — Node 22+)
#   - symlink bin/sss-get.mjs into ~/.local/bin
#   - register sss as an MCP server in ~/.codex/config.toml (if Codex is installed)
#
# Re-running is idempotent: it overwrites the systemd unit, regenerates
# the API key (so previously issued tokens are invalidated), and re-syncs
# the symlink.
set -euo pipefail

REPO="https://github.com/megamen32/simple-secret-storage.git"
INSTALL_DIR="$HOME/agents-projects/simple-secret-storage"
API_KEY_FILE="$HOME/.config/sss-mcp/api-key.env"
SYSTEMD_UNIT_SRC="$INSTALL_DIR/systemd/sss.service"
SYSTEMD_UNIT_DST="/etc/systemd/system/sss.service"
LOCAL_BIN="$HOME/.local/bin"
CODEX_CONFIG="$HOME/.codex/config.toml"

say() { printf '\033[1;34m==>\033[0m %s\n' "$*"; }
warn() { printf '\033[1;33m[warn]\033[0m %s\n' "$*" >&2; }
die() { printf '\033[1;31m[err]\033[0m %s\n' "$*" >&2; exit 1; }

# --- 1. Pre-flight ---
say "Pre-flight checks"
command -v git >/dev/null || die "git not found"
command -v npm >/dev/null || die "npm not found"
NODE_BIN="$(command -v node || true)"
if [ -z "$NODE_BIN" ]; then die "node not found"; fi
NODE_MAJOR="$("$NODE_BIN" -p 'process.versions.node.split(".")[0]')"
if [ "$NODE_MAJOR" -lt 20 ]; then
  die "node >= 20 required (found $NODE_MAJOR in $NODE_BIN)"
fi
say "node $("$NODE_BIN" --version) at $NODE_BIN"
command -v systemctl >/dev/null || die "systemctl not found (not a systemd host?)"

# --- 2. Clone or update the repo ---
mkdir -p "$(dirname "$INSTALL_DIR")"
if [ -d "$INSTALL_DIR/.git" ]; then
  say "Updating existing repo at $INSTALL_DIR"
  git -C "$INSTALL_DIR" pull --ff-only
else
  say "Cloning $REPO into $INSTALL_DIR"
  git clone "$REPO" "$INSTALL_DIR"
fi

# --- 3. npm ci + build ---
say "Installing dependencies and building"
(cd "$INSTALL_DIR" && npm ci)
(cd "$INSTALL_DIR" && npm run build)

# --- 4. Generate API key ---
say "Generating bearer token"
mkdir -p "$HOME/.config/sss-mcp"
chmod 700 "$HOME/.config/sss-mcp"
NEW_KEY="$(openssl rand -hex 32)"
umask 077
{
  printf '# Generated by simple-secret-storage install.sh on %s\n' "$(date -u +%FT%TZ)"
  printf 'SSS_API_KEY=%s\n' "$NEW_KEY"
} > "$API_KEY_FILE"
chmod 600 "$API_KEY_FILE"

# --- 5. Systemd unit (path-aware) ---
say "Installing systemd unit"
TMP_UNIT="$(mktemp)"
sed -e "s|^EnvironmentFile=.*|EnvironmentFile=$API_KEY_FILE|" \
    -e "s|^ExecStart=.*|ExecStart=$NODE_BIN $INSTALL_DIR/dist/server.js|" \
    -e "s|^WorkingDirectory=.*|WorkingDirectory=$INSTALL_DIR|" \
    "$SYSTEMD_UNIT_SRC" > "$TMP_UNIT"
sudo install -m 0644 "$TMP_UNIT" "$SYSTEMD_UNIT_DST"
rm -f "$TMP_UNIT"
sudo systemctl daemon-reload
sudo systemctl enable --now sss.service

# --- 6. sss-get symlink ---
say "Linking sss-get into ~/.local/bin"
mkdir -p "$LOCAL_BIN"
ln -sf "$INSTALL_DIR/bin/sss-get.mjs" "$LOCAL_BIN/sss-get"
ln -sf "$INSTALL_DIR/bin/sss-run.mjs" "$LOCAL_BIN/sss-run"

# --- 7. Codex MCP registration (best-effort) ---
CODEX_CONFIG="$HOME/.codex/config.toml"
if [ -f "$CODEX_CONFIG" ] && grep -q '^\[mcp_servers\.sss\]' "$CODEX_CONFIG"; then
  say "Codex already has [mcp_servers.sss] — leaving as-is"
elif [ -f "$CODEX_CONFIG" ]; then
  say "Registering sss in Codex MCP config"
  cp "$CODEX_CONFIG" "$CODEX_CONFIG.bak.$(date -u +%Y%m%dT%H%M%SZ)"
  cat >> "$CODEX_CONFIG" <<EOF

# Added by simple-secret-storage install.sh
[mcp_servers.sss]
url = "https://pswd.bezrabotnyi.com/mcp"
bearer_token_env_var = "SSS_API_KEY"
EOF
else
  warn "Codex config not found at $CODEX_CONFIG — skip Codex integration"
fi

# Also source the env file from .profile so login shells pick up SSS_API_KEY.
PROFILE="$HOME/.profile"
if [ -f "$PROFILE" ] && ! grep -q 'sss-mcp/api-key.env' "$PROFILE"; then
  say "Adding SSS_API_KEY sourcing to $PROFILE"
  cat >> "$PROFILE" <<'EOF'

# SSS MCP server — API key for the local Codex connection.
if [ -z "${SSS_API_KEY:-}" ] && [ -f "$HOME/.config/sss-mcp/api-key.env" ]; then
  set -a
  . "$HOME/.config/sss-mcp/api-key.env"
  set +a
fi
EOF
fi

# --- 8. Summary ---
say "Done"
cat <<EOF

  Web UI:    https://pswd.bezrabotnyi.com/
  MCP URL:   https://pswd.bezrabotnyi.com/mcp
  Bearer:    $NEW_KEY
  Repo:      $INSTALL_DIR
  Config:    $API_KEY_FILE
  Service:   systemctl status sss
  CLI:       $(command -v sss-get || echo "$LOCAL_BIN/sss-get")

Verify:
  sss-get test_password   # if you've stored one
  curl -sN https://pswd.bezrabotnyi.com/ | head

EOF